spring:
  application:
    name: lms-entrepreneurship-school-backend-app
  database:
    master:
      url: ${MASTER_URL}
    slave:
      url: ${SLAVE_URL}
  r2dbc:
    #    for liquibase schema changing
    url: r2dbc:postgresql://localhost:5433/lms_db?pooled=false
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}

  liquibase:
    change-log: classpath:liquibase/changelog.xml
    enabled: true

  docker:
    compose:
      enabled: false

application:
  auth:
    route: '/api/v1/auth'
    enabled: false
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400 # 1 day

mail:
  sending:
    enabled: false
  from: ${SMTP_USERNAME}
  smtp:
    auth: true
    host: smtp.yandex.com
    port: 465
    ssl:
      port: 465
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    debug: false


logging:
  level:
    org.springframework.r2dbc: TRACE
    ru.hse.lmsteam: DEBUG

server:
  port: 3000
  compression:
    enabled: true
springdoc:
  show-actuator: true