spring:
  main:
    web-application-type: reactive
  application:
    name: lms-entrepreneurship-school-backend-app
  database:
    master:
      url: ${MASTER_URL}
    slave:
      url: ${SLAVE_URL}
  r2dbc:
    #    for liquibase schema changing
    url: ${R2DBC_LIQUIBASE_URL}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    pool:
      enabled: true
      initial-size: 10
      max-size: 20

  liquibase:
    change-log: classpath:liquibase/changelog.xml
    enabled: true

  docker:
    compose:
      enabled: false

  pageable:
    default-page: 0
    default-page-size: 20
    max-page-size: 100

management:
  endpoints:
    web:
      exposure:
        include: '*'

application:
  auth:
    route: '/api/v1/auth'
    enabled: false
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION}

mail:
  sending:
    enabled: ${MAIL_SENDING_ENABLED}
  from: ${SMTP_USERNAME}
  smtp:
    auth: true
    host: smtp.yandex.com
    port: 465
    ssl:
      port: 465
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    debug: false


logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.springframework.r2dbc: TRACE
    ru.hse.lmsteam: DEBUG

server:
  port: ${SERVER_PORT}
  compression:
    enabled: true
  http2:
    enabled: true
springdoc:
  show-actuator: true