global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ '172.17.0.1:9090' ]

  - job_name: 'lms_backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '172.17.0.1:3000' ]
        labels:
          application: "Backend"
